// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mylymcmivtxsaxichhyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15bHltY21pdnR4c2F4aWNoaHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Mzk5NTEsImV4cCI6MjA3MzQxNTk1MX0.W55pjHPItnuGJKEoHMxue-OcF2h2QGIjYtCAc0DJLZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});